{% set version = "2024.6.0" %}


package:
  name: dask-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask/dask-{{ version }}.tar.gz
  sha256: 6882ce7e485336d707e540080ed48e01f9c09485d52a2928ea05f9a9e44bb433

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask = dask.__main__:main

requirements:
  host:
    - python >=3.9
    - pip
    - versioneer =0.29
    - tomli

  run:
    - python >=3.9
    - click >=8.1
    - cloudpickle >=1.5.0
    - fsspec >=2021.09.0
    - packaging >=20.0
    - partd >=1.2.0
    - pyyaml >=5.3.1
    - toolz >=0.10.0
    - importlib_metadata >=4.13.0

test:
  imports:
    - dask
  commands:
    - pip check
    - dask --help
    - dask docs --help
    - dask info --help
    - dask info versions --help
  requires:
    - pip

about:
  home: https://github.com/dask/dask/
  summary: Parallel PyData with Task Scheduling
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - dask/array/NUMPY_LICENSE.txt
  doc_url: https://dask.org/
  dev_url: https://github.com/dask/dask

extra:
  recipe-maintainers:
    - jakirkham
    - jcrist
    - martindurant
    - mrocklin
    - pitrou
    - shoyer
    - sinhrks
    - tomaugspurger
    - jrbourbeau
    - charlesbluca
    - fjetter
